api:

    ## A custom name for the API provider
    ## --
    ## 
    my_api_v1:

        ## API Version
        ## --
        ## Set the value of the API version, used to generate the URI
        ## > e.g.: site.com/api/v1/books
        ##
        ## @var int
        ## @required
        ##
        version: 1

        ## Defines how links in the response will be generated
        ## --
        ##
        links:

            ## Links state
            ## --
            ## If true, add the entity link to the response
            ## 
            ## @var bool
            ## @default true
            ## 
            state: true

            ## Links absolute
            ## --
            ## If true, generate an absolute link
            ## 
            ## @var bool
            ## @default true
            ## 
            absolute: true

        ## Response pagination settings
        ## --
        ##
        pagination:

            ## Pagination state
            ## --
            ## If true, the response will paginate
            ## 
            ## @var bool
            ## @default true
            ## 
            state: true

            ## Items per page
            ## --
            ## Number of items per page
            ## 
            ## @var integer
            ## @default 10
            ## 
            items_per_page: 10

        ## Search by API settings
        ## --
        ##
        search:

            ## Is the search by the API is allowed
            ## --
            ## If true, the search is allowed
            ## 
            ## @var bool
            ## @default true
            ## 
            allowed: true

            ## The search parameter of the URL
            ## --
            ## e.g.: site.com/api/v1/?q=xxx
            ## 
            ## @var string
            ## @default "q"
            ## 
            param: q

        ## Index entities
        ## --
        ##
        collections:

            # authors:
            #     class: App\Entity\Book\Author\Author
            #     privileges:
            #         admin:
            #             granted: null

            ## Name of the collection
            ## --
            ##
            all_items:

                ## Entity Class 
                ## --
                ## The name of the entity of the collection
                ##
                ## @var string
                ## @required
                ## 
                class: App\Entity\Item

                ## Repository methods
                ## --
                ## Repository methods apply to retrieve the list or one of entities
                ## 
                ## @var array
                ## 
                repository_methods:
                    findAll: findBy
                    # findOne: find

                ## URL Paths for plural or singular item
                ## --
                ## Will be automatically generated if not set
                ## 
                paths:
                    
                    ## Singular path
                    ## --
                    ## 
                    ## @var string
                    ## @default singular of App\Entity\Book\Book\Book
                    ## 
                    # singular: book
                    
                    ## Plural path
                    ## --
                    ## 
                    ## @var string
                    ## @default plural of App\Entity\Book\Book\Book
                    ## 
                    # plural: books

                ## Serializer Groups
                ## --
                ## Groups ID for serialization
                ##
                ## @var string[]
                ## @default []
                ## 
                # scope: ['book']

                ## Response default sorter
                ## --
                ## Override this default sorter with the sorter param in the URL
                ## e.g.: site.com/api/v1/books/?sorter=title:DESC,price:ASC
                ##         
                ## e.g.: title: 
                ##          order: ASC
                ##
                ## @var array
                ## 
                sorter:
                    name: 
                        order: ASC
                    # price: 
                    #     order: DESC

                ## Privileges access
                ## --
                ##
                privileges:

                    ## Name of the privilege
                    ## --
                    ## 
                    public:

                        ## Granted / Role
                        ## --
                        ## 
                        ## @var string
                        ## @default null
                        ## 
                        granted: null #'PUBLIC_ACCESS'

                        ## Allowed methods
                        ## --
                        ## 
                        ## @var enum[]
                        ## @default ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
                        ## 
                        # methods: ['GET']

                    # private:
                    #     granted: 'ROLE_USER'
                    #     methods: ['GET','POST','PUT','PATCH']

                    # admin:
                    #     granted: 'ROLE_ADMIN'
                    #     methods: ['GET','POST','PUT','PATCH','DELETE']

                ## Privileges access
                ## --
                ##
                search:

                    ## Exclude
                    ## --
                    ## Exclude the entity from the search request
                    ## 
                    ## @var bool
                    ## @default false
                    ## 
                    excluded: false

                    ## Criteria
                    ## --
                    ## Used to generate a WHERE clause of the query
                    ## 
                    ## @var array
                    ## 
                    criteria:

                        ## For the property "title"
                        ## sql : ... WHERE `title` LIKE '%$expression%'
                        name:
                            match: like
                        # description:
                        #     match: like
    
    # my_api_v2:
    #     version: 2




    my_api_v2:
        version: 2
        links:
            state: true
            absolute: true
        pagination:
            state: true
            items_per_page: 3
        search:
            allowed: true
            param: q
        collections:
            all_books:
                class: App\Entity\Item
                repository_methods:
                    # findAll: findBy
                    # findOne: find
                paths:
                    # singular: book  //site.com/api/v2/book
                    # plural: books   //site.com/api/v2/livres
                # serializer_groups: ['book']
                sorter:
                    name: 
                        order: ASC
                privileges:
                    public:
                        granted: 'PUBLIC_ACCESS'
                        ## @default ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
                        methods: ['GET']
                    # private:
                    #     granted: 'ROLE_USER'
                    #     methods: ['GET','POST','PUT','PATCH']
                search:
                    excluded: false
                    criteria:
                        name:
                            match: like
                        # description:
                        #     match: like
