services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\Api\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    OSW3\Api\Routing\RouteLoader:
        tags:
            - { name: routing.loader }
