services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\Api\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Resources/'

    OSW3\Api\Loader\RouteLoader:
        tags:
            - { name: routing.loader }

    OSW3\Api\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
